# Generated by Django 6.1 on 2026-08-14 14:52

import catalog.models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(catalog.models.CategorySidebarMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='PartSetIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SubcategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=(catalog.models.CategorySidebarMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='ComponentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('signal_type', models.CharField(blank=True, max_length=100)),
                ('docs_about', wagtail.fields.RichTextField(blank=True, verbose_name='About')),
                ('docs_what_it_is', wagtail.fields.RichTextField(blank=True, verbose_name='What it is')),
                ('docs_when_to_use_it', wagtail.fields.RichTextField(blank=True, verbose_name='When to use it')),
                ('docs_how_it_works', wagtail.fields.RichTextField(blank=True, verbose_name='How it works')),
                ('docs_how_to_use_it', wagtail.fields.RichTextField(blank=True, verbose_name='How to use it')),
                ('docs_getting_started', wagtail.fields.RichTextField(blank=True, verbose_name='Getting started')),
                ('docs_resources', wagtail.fields.RichTextField(blank=True, verbose_name='Resources')),
                ('hidden', models.BooleanField(default=False, help_text='Keep published but omit from category and set listings.')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=(catalog.models.CategorySidebarMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='PartRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_part_links', to='catalog.componentpage')),
                ('related_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.componentpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartSetPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='componentpage',
            name='part_sets',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='A part may belong to several sets.', related_name='parts', to='catalog.partsetpage'),
        ),
        migrations.CreateModel(
            name='StockedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('part_number', models.CharField(db_index=True, help_text='Must match the part number in ioref-inventory.', max_length=32, unique=True)),
                ('label', models.CharField(blank=True, help_text='What distinguishes this one, e.g. "10pF". Leave blank if the component has only one.', max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocked_parts', to='catalog.componentpage')),
            ],
            options={
                'verbose_name': 'stocked part',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
