# Generated by Django 6.1 on 2026-08-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentpage',
            name='code_caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='componentpage',
            name='code_example',
            field=models.TextField(blank=True, help_text='Plain text. Rendered as a code block under Getting started.', verbose_name='Code example'),
        ),
    ]
