# Generated by Django 6.1 on 2026-08-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_componentpage_code_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentpage',
            name='inventory_group',
            field=models.SlugField(blank=True, help_text="Slug of an ioref-inventory group, e.g. 'potentiometers'. When set, the stocked parts below are read from inventory instead of being listed by hand.", max_length=100),
        ),
    ]
