# Generated by Django 6.1 on 2026-08-17 20:06

import django.db.models.deletion
import wagtailmarkdown.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_componentpage_inventory_group'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentpage',
            name='code_caption',
        ),
        migrations.RemoveField(
            model_name='componentpage',
            name='code_example',
        ),
        migrations.AlterField(
            model_name='componentpage',
            name='docs_about',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='componentpage',
            name='docs_getting_started',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, verbose_name='Getting started'),
        ),
        migrations.AlterField(
            model_name='componentpage',
            name='docs_how_it_works',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, verbose_name='How it works'),
        ),
        migrations.AlterField(
            model_name='componentpage',
            name='docs_how_to_use_it',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, verbose_name='How to use it'),
        ),
        migrations.AlterField(
            model_name='componentpage',
            name='docs_resources',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, verbose_name='Resources'),
        ),
        migrations.AlterField(
            model_name='componentpage',
            name='docs_what_it_is',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, verbose_name='What it is'),
        ),
        migrations.AlterField(
            model_name='componentpage',
            name='docs_when_to_use_it',
            field=wagtailmarkdown.fields.MarkdownField(blank=True, verbose_name='When to use it'),
        ),
        migrations.CreateModel(
            name='MediaAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_index=True, max_length=255, unique=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_aliases', to='wagtailimages.image')),
            ],
            options={
                'verbose_name_plural': 'media aliases',
            },
        ),
    ]
