# Generated by Django 6.1 on 2026-08-17 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_componentpage_code_caption_and_more'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaalias',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_aliases', to='wagtaildocs.document'),
        ),
        migrations.AlterField(
            model_name='mediaalias',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_aliases', to='wagtailimages.image'),
        ),
        migrations.AddConstraint(
            model_name='mediaalias',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('document__isnull', True), ('image__isnull', False)), models.Q(('document__isnull', False), ('image__isnull', True)), _connector='OR'), name='alias_points_at_exactly_one_target'),
        ),
    ]
