"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
from pathlib import Path

import environ

PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")

# dev.py and production.py both import from here with `from .base import *`.
# dev.py overrides both of these unconditionally with its own hardcoded
# values, so this default only ever takes effect if production.py is run
# without SECRET_KEY set in the environment -- which .env.example documents
# as required, but nothing previously enforced.
SECRET_KEY = env("SECRET_KEY", default="django-insecure-dev-only-do-not-deploy")
ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "catalog",
    "stock",
    "django.contrib.staticfiles",
]

# No sessions, auth, messages or admin. Nothing here has a user: the guides are
# public, the inventory views are read-only, and the content is edited by
# committing a file. See "No database" below.
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
            PROJECT_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# ---------------------------------------------------------------------------
# Content
#
# The guides are 130 markdown files with YAML frontmatter, read once at
# startup. Editing the site means editing a file and committing it.
# ---------------------------------------------------------------------------
CONTENT_DIR = env("CONTENT_DIR", default=BASE_DIR / "content")


# ---------------------------------------------------------------------------
# No database
#
# There is nothing to store. Guide content is files, stock lives in
# ioref-inventory and arrives over its API, and there are no user accounts
# because there is nothing to log in to. An empty DATABASES is a supported
# configuration, and it is what stops a schema quietly reappearing: anything
# that wants a model has to justify reintroducing a database first.
# ---------------------------------------------------------------------------
DATABASES = {}


# ---------------------------------------------------------------------------
# ioref-inventory
#
# The only channel to the inventory application, and now the only thing this
# site talks to at all. Read-scoped key: nothing here can write stock.
# Generate it in the inventory admin under "API keys" and put it in the
# environment, never in code.
# ---------------------------------------------------------------------------
INVENTORY_API_URL = env("INVENTORY_API_URL", default="http://127.0.0.1:8765")
INVENTORY_API_KEY = env("INVENTORY_API_KEY", default="")
INVENTORY_API_TIMEOUT = env.float("INVENTORY_API_TIMEOUT", default=3.0)
# Stock changes a few times a day at most; part pages are the busiest on the
# site. Short cache keeps inventory out of the hot path without going stale.
INVENTORY_CACHE_SECONDS = env.int("INVENTORY_CACHE_SECONDS", default=120)


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    BASE_DIR / "static",
    PROJECT_DIR / "static",
]

# Not BASE_DIR/"static" -- that is a source directory here, and collectstatic
# must not write into a directory it also reads from.
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "/static/"

# Served at the root of the URL space rather than under STATIC_URL, because the
# guide prose references its diagrams as /images/parts/<file> and rewriting
# 61 paths across the content is exactly what storing markdown was meant to
# avoid. WhiteNoise serves this directory in development and production alike.
#
# Deliberately outside STATICFILES_DIRS: collectstatic would otherwise copy all
# 84 MB into staticfiles/ as a second set, and the manifest storage would then
# hash the names, which is precisely what the prose cannot follow.
WHITENOISE_ROOT = BASE_DIR / "public"
WHITENOISE_INDEX_FILE = False

# Default storage settings
# See https://docs.djangoproject.com/en/6.1/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
